package com.app.model;
// Generated 2016-3-29 9:01:01 by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Customer generated by hbm2java
 */
@Entity
@Table(name = "tip", catalog = "tip")
public class Tip implements java.io.Serializable {

	private long id;
	private long uid;
	private int version;
	private long tag1id;
	private long tag2id;
	private long tag3id;
	private String title;
	private int state;
	private String content;
	private String url;
	private String comment;
	
	public Tip() {
	}

	public Tip(long id) {
		this.id = id;
	}

	

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Column(name = "tag1id", unique = true, nullable = false)
	public long getTag1id() {
		return this.tag1id;
	}

	public void setTag1id(long tag1id) {
		this.tag1id = tag1id;
	}
	
	@Column(name = "tag2id", unique = true, nullable = false)
	public long getTag2id() {
		return this.tag2id;
	}

	public void setTag2id(long tag2id) {
		this.tag2id = tag2id;
	}
	
	@Column(name = "tag3id", unique = true, nullable = false)
	public long getTag3id() {
		return this.tag3id;
	}

	public void setTag3id(long tag3id) {
		this.tag3id = tag3id;
	}
	
	
	

	@Column(name = "uid", unique = true, nullable = false)
	public long getUid() {
		return this.uid;
	}

	public void setUid(long uid) {
		this.uid = uid;
	}
	
	
	@Column(name = "version", unique = true, nullable = false)
	public int getVersion() {
		return this.version;
	}

	public void setVersion(int version) {
		this.version = version;
	}
	
	@Column(name = "state", unique = true, nullable = false)
	public int getState() {
		return this.state;
	}

	public void setState(int state) {
		this.state = state;
	}

	@Column(name = "title")
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}
	
	@Column(name = "content")
	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}
	
	@Column(name = "comment")
	public String getComment() {
		return this.comment;
	}

	public void setComment(String comment) {
		this.comment = comment;
	}
	
	@Column(name = "url")
	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

}
