package com.app.model;
// Generated 2016-3-29 9:01:01 by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Customer generated by hbm2java
 */
@Entity
@Table(name = "user", catalog = "tip")
public class User implements java.io.Serializable {

	private long id;
	private String name;
	private String pwd;

	public User() {
	}

	public User(long id) {
		this.id = id;
	}

	public User(long id, String name, String mobile, String email, String pwd) {
		this.id = id;
		this.name = name;
		this.pwd = pwd;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Column(name = "name")
	public String getname() {
		return this.name;
	}

	public void setname(String name) {
		this.name = name;
	}

	

	@Column(name = "pwd")
	public String getPwd() {
		return this.pwd;
	}

	public void setPwd(String pwd) {
		this.pwd = pwd;
	}

}
